# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Wed Oct 05 12:11:46 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1915, 1104)
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1893, 1080))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1871, 1061))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_primary_sweep = QtGui.QGroupBox(self.tab)
        self.groupBox_primary_sweep.setGeometry(QtCore.QRect(0, 10, 931, 1021))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_primary_sweep.setFont(font)
        self.groupBox_primary_sweep.setObjectName(_fromUtf8("groupBox_primary_sweep"))
        self.groupBox_primary_device = QtGui.QGroupBox(self.groupBox_primary_sweep)
        self.groupBox_primary_device.setGeometry(QtCore.QRect(20, 30, 341, 331))
        self.groupBox_primary_device.setTitle(_fromUtf8(""))
        self.groupBox_primary_device.setObjectName(_fromUtf8("groupBox_primary_device"))
        self.label_visaname_1 = QtGui.QLabel(self.groupBox_primary_device)
        self.label_visaname_1.setGeometry(QtCore.QRect(30, 240, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_1.setFont(font)
        self.label_visaname_1.setObjectName(_fromUtf8("label_visaname_1"))
        self.comboBox_visa_1 = QtGui.QComboBox(self.groupBox_primary_device)
        self.comboBox_visa_1.setGeometry(QtCore.QRect(20, 150, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_1.setFont(font)
        self.comboBox_visa_1.setObjectName(_fromUtf8("comboBox_visa_1"))
        self.pushButton_update_1 = QtGui.QPushButton(self.groupBox_primary_device)
        self.pushButton_update_1.setGeometry(QtCore.QRect(240, 200, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_1.setFont(font)
        self.pushButton_update_1.setObjectName(_fromUtf8("pushButton_update_1"))
        self.pushButton_select_1 = QtGui.QPushButton(self.groupBox_primary_device)
        self.pushButton_select_1.setGeometry(QtCore.QRect(40, 200, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_1.setFont(font)
        self.pushButton_select_1.setObjectName(_fromUtf8("pushButton_select_1"))
        self.label_chooseVisa_1 = QtGui.QLabel(self.groupBox_primary_device)
        self.label_chooseVisa_1.setGeometry(QtCore.QRect(30, 120, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_1.setFont(font)
        self.label_chooseVisa_1.setObjectName(_fromUtf8("label_chooseVisa_1"))
        self.label_visa_1 = QtGui.QLabel(self.groupBox_primary_device)
        self.label_visa_1.setGeometry(QtCore.QRect(10, 270, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_1.setFont(font)
        self.label_visa_1.setText(_fromUtf8(""))
        self.label_visa_1.setObjectName(_fromUtf8("label_visa_1"))
        self.pushButton_close_1 = QtGui.QPushButton(self.groupBox_primary_device)
        self.pushButton_close_1.setGeometry(QtCore.QRect(140, 200, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_1.setFont(font)
        self.pushButton_close_1.setObjectName(_fromUtf8("pushButton_close_1"))
        self.label_device_1 = QtGui.QLabel(self.groupBox_primary_device)
        self.label_device_1.setGeometry(QtCore.QRect(30, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_device_1.setFont(font)
        self.label_device_1.setObjectName(_fromUtf8("label_device_1"))
        self.comboBox_device_1 = QtGui.QComboBox(self.groupBox_primary_device)
        self.comboBox_device_1.setGeometry(QtCore.QRect(20, 40, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_device_1.setFont(font)
        self.comboBox_device_1.setObjectName(_fromUtf8("comboBox_device_1"))
        self.comboBox_device_1.addItem(_fromUtf8(""))
        self.comboBox_device_1.addItem(_fromUtf8(""))
        self.comboBox_device_1.addItem(_fromUtf8(""))
        self.comboBox_device_1.addItem(_fromUtf8(""))
        self.groupBox_input_1 = QtGui.QGroupBox(self.groupBox_primary_sweep)
        self.groupBox_input_1.setGeometry(QtCore.QRect(380, 30, 541, 271))
        self.groupBox_input_1.setTitle(_fromUtf8(""))
        self.groupBox_input_1.setObjectName(_fromUtf8("groupBox_input_1"))
        self.label_47 = QtGui.QLabel(self.groupBox_input_1)
        self.label_47.setGeometry(QtCore.QRect(20, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.textEdit_steps_1 = QtGui.QTextEdit(self.groupBox_input_1)
        self.textEdit_steps_1.setGeometry(QtCore.QRect(20, 40, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_steps_1.setFont(font)
        self.textEdit_steps_1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_steps_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_steps_1.setTabStopWidth(80)
        self.textEdit_steps_1.setCursorWidth(2)
        self.textEdit_steps_1.setObjectName(_fromUtf8("textEdit_steps_1"))
        self.label_2 = QtGui.QLabel(self.groupBox_input_1)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_steps_1 = QtGui.QLabel(self.groupBox_input_1)
        self.label_steps_1.setGeometry(QtCore.QRect(130, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_steps_1.setFont(font)
        self.label_steps_1.setText(_fromUtf8(""))
        self.label_steps_1.setObjectName(_fromUtf8("label_steps_1"))
        self.pushButton_clear_1 = QtGui.QPushButton(self.groupBox_input_1)
        self.pushButton_clear_1.setEnabled(False)
        self.pushButton_clear_1.setGeometry(QtCore.QRect(400, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clear_1.setFont(font)
        self.pushButton_clear_1.setObjectName(_fromUtf8("pushButton_clear_1"))
        self.pushButton_plot_1 = QtGui.QPushButton(self.groupBox_input_1)
        self.pushButton_plot_1.setGeometry(QtCore.QRect(290, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_plot_1.setFont(font)
        self.pushButton_plot_1.setObjectName(_fromUtf8("pushButton_plot_1"))
        self.textEdit_input_1 = QtGui.QTextEdit(self.groupBox_input_1)
        self.textEdit_input_1.setGeometry(QtCore.QRect(230, 40, 291, 171))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_input_1.setFont(font)
        self.textEdit_input_1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_input_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_input_1.setTabStopWidth(80)
        self.textEdit_input_1.setCursorWidth(2)
        self.textEdit_input_1.setObjectName(_fromUtf8("textEdit_input_1"))
        self.label_3 = QtGui.QLabel(self.groupBox_input_1)
        self.label_3.setGeometry(QtCore.QRect(230, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox_stepplot_1 = QtGui.QGroupBox(self.groupBox_primary_sweep)
        self.groupBox_stepplot_1.setGeometry(QtCore.QRect(20, 360, 901, 651))
        self.groupBox_stepplot_1.setObjectName(_fromUtf8("groupBox_stepplot_1"))
        self.widget_1 = QtGui.QWidget(self.groupBox_stepplot_1)
        self.widget_1.setGeometry(QtCore.QRect(0, 10, 901, 651))
        self.widget_1.setObjectName(_fromUtf8("widget_1"))
        self.mplwidget_1 = MatplotlibWidget(self.widget_1)
        self.mplwidget_1.setGeometry(QtCore.QRect(410, 320, 16, 16))
        self.mplwidget_1.setObjectName(_fromUtf8("mplwidget_1"))
        self.groupBox_condition_1 = QtGui.QGroupBox(self.groupBox_primary_sweep)
        self.groupBox_condition_1.setGeometry(QtCore.QRect(380, 300, 541, 61))
        self.groupBox_condition_1.setObjectName(_fromUtf8("groupBox_condition_1"))
        self.label_condition_1 = QtGui.QLabel(self.groupBox_condition_1)
        self.label_condition_1.setGeometry(QtCore.QRect(10, 20, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_condition_1.setFont(font)
        self.label_condition_1.setText(_fromUtf8(""))
        self.label_condition_1.setObjectName(_fromUtf8("label_condition_1"))
        self.groupBox_secondary_sweep = QtGui.QGroupBox(self.tab)
        self.groupBox_secondary_sweep.setGeometry(QtCore.QRect(930, 10, 931, 1021))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_secondary_sweep.setFont(font)
        self.groupBox_secondary_sweep.setObjectName(_fromUtf8("groupBox_secondary_sweep"))
        self.groupBox_secondaey_device = QtGui.QGroupBox(self.groupBox_secondary_sweep)
        self.groupBox_secondaey_device.setGeometry(QtCore.QRect(20, 30, 341, 331))
        self.groupBox_secondaey_device.setTitle(_fromUtf8(""))
        self.groupBox_secondaey_device.setObjectName(_fromUtf8("groupBox_secondaey_device"))
        self.tabWidget_visa = QtGui.QTabWidget(self.groupBox_secondaey_device)
        self.tabWidget_visa.setGeometry(QtCore.QRect(10, 90, 321, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_visa.setFont(font)
        self.tabWidget_visa.setObjectName(_fromUtf8("tabWidget_visa"))
        self.tab_228 = QtGui.QWidget()
        self.tab_228.setObjectName(_fromUtf8("tab_228"))
        self.label_chooseVisa_2_1 = QtGui.QLabel(self.tab_228)
        self.label_chooseVisa_2_1.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_1.setFont(font)
        self.label_chooseVisa_2_1.setObjectName(_fromUtf8("label_chooseVisa_2_1"))
        self.pushButton_select_2_1 = QtGui.QPushButton(self.tab_228)
        self.pushButton_select_2_1.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_1.setFont(font)
        self.pushButton_select_2_1.setObjectName(_fromUtf8("pushButton_select_2_1"))
        self.comboBox_visa_2_1 = QtGui.QComboBox(self.tab_228)
        self.comboBox_visa_2_1.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_1.setFont(font)
        self.comboBox_visa_2_1.setObjectName(_fromUtf8("comboBox_visa_2_1"))
        self.label_visaname_2_1 = QtGui.QLabel(self.tab_228)
        self.label_visaname_2_1.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_1.setFont(font)
        self.label_visaname_2_1.setObjectName(_fromUtf8("label_visaname_2_1"))
        self.pushButton_close_2_1 = QtGui.QPushButton(self.tab_228)
        self.pushButton_close_2_1.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_1.setFont(font)
        self.pushButton_close_2_1.setObjectName(_fromUtf8("pushButton_close_2_1"))
        self.pushButton_update_2_1 = QtGui.QPushButton(self.tab_228)
        self.pushButton_update_2_1.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_1.setFont(font)
        self.pushButton_update_2_1.setObjectName(_fromUtf8("pushButton_update_2_1"))
        self.label_visa_2_1 = QtGui.QLabel(self.tab_228)
        self.label_visa_2_1.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_1.setFont(font)
        self.label_visa_2_1.setText(_fromUtf8(""))
        self.label_visa_2_1.setObjectName(_fromUtf8("label_visa_2_1"))
        self.tabWidget_visa.addTab(self.tab_228, _fromUtf8(""))
        self.tab_229 = QtGui.QWidget()
        self.tab_229.setObjectName(_fromUtf8("tab_229"))
        self.comboBox_visa_2_2 = QtGui.QComboBox(self.tab_229)
        self.comboBox_visa_2_2.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_2.setFont(font)
        self.comboBox_visa_2_2.setObjectName(_fromUtf8("comboBox_visa_2_2"))
        self.label_visa_2_2 = QtGui.QLabel(self.tab_229)
        self.label_visa_2_2.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_2.setFont(font)
        self.label_visa_2_2.setText(_fromUtf8(""))
        self.label_visa_2_2.setObjectName(_fromUtf8("label_visa_2_2"))
        self.label_chooseVisa_2_2 = QtGui.QLabel(self.tab_229)
        self.label_chooseVisa_2_2.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_2.setFont(font)
        self.label_chooseVisa_2_2.setObjectName(_fromUtf8("label_chooseVisa_2_2"))
        self.label_visaname_2_2 = QtGui.QLabel(self.tab_229)
        self.label_visaname_2_2.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_2.setFont(font)
        self.label_visaname_2_2.setObjectName(_fromUtf8("label_visaname_2_2"))
        self.pushButton_update_2_2 = QtGui.QPushButton(self.tab_229)
        self.pushButton_update_2_2.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_2.setFont(font)
        self.pushButton_update_2_2.setObjectName(_fromUtf8("pushButton_update_2_2"))
        self.pushButton_select_2_2 = QtGui.QPushButton(self.tab_229)
        self.pushButton_select_2_2.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_2.setFont(font)
        self.pushButton_select_2_2.setObjectName(_fromUtf8("pushButton_select_2_2"))
        self.pushButton_close_2_2 = QtGui.QPushButton(self.tab_229)
        self.pushButton_close_2_2.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_2.setFont(font)
        self.pushButton_close_2_2.setObjectName(_fromUtf8("pushButton_close_2_2"))
        self.tabWidget_visa.addTab(self.tab_229, _fromUtf8(""))
        self.tab_230 = QtGui.QWidget()
        self.tab_230.setObjectName(_fromUtf8("tab_230"))
        self.comboBox_visa_2_3 = QtGui.QComboBox(self.tab_230)
        self.comboBox_visa_2_3.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_3.setFont(font)
        self.comboBox_visa_2_3.setObjectName(_fromUtf8("comboBox_visa_2_3"))
        self.label_visa_2_3 = QtGui.QLabel(self.tab_230)
        self.label_visa_2_3.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_3.setFont(font)
        self.label_visa_2_3.setText(_fromUtf8(""))
        self.label_visa_2_3.setObjectName(_fromUtf8("label_visa_2_3"))
        self.label_chooseVisa_2_3 = QtGui.QLabel(self.tab_230)
        self.label_chooseVisa_2_3.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_3.setFont(font)
        self.label_chooseVisa_2_3.setObjectName(_fromUtf8("label_chooseVisa_2_3"))
        self.label_visaname_2_3 = QtGui.QLabel(self.tab_230)
        self.label_visaname_2_3.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_3.setFont(font)
        self.label_visaname_2_3.setObjectName(_fromUtf8("label_visaname_2_3"))
        self.pushButton_update_2_3 = QtGui.QPushButton(self.tab_230)
        self.pushButton_update_2_3.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_3.setFont(font)
        self.pushButton_update_2_3.setObjectName(_fromUtf8("pushButton_update_2_3"))
        self.pushButton_select_2_3 = QtGui.QPushButton(self.tab_230)
        self.pushButton_select_2_3.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_3.setFont(font)
        self.pushButton_select_2_3.setObjectName(_fromUtf8("pushButton_select_2_3"))
        self.pushButton_close_2_3 = QtGui.QPushButton(self.tab_230)
        self.pushButton_close_2_3.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_3.setFont(font)
        self.pushButton_close_2_3.setObjectName(_fromUtf8("pushButton_close_2_3"))
        self.tabWidget_visa.addTab(self.tab_230, _fromUtf8(""))
        self.tab_231 = QtGui.QWidget()
        self.tab_231.setObjectName(_fromUtf8("tab_231"))
        self.comboBox_visa_2_4 = QtGui.QComboBox(self.tab_231)
        self.comboBox_visa_2_4.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_4.setFont(font)
        self.comboBox_visa_2_4.setObjectName(_fromUtf8("comboBox_visa_2_4"))
        self.label_visa_2_4 = QtGui.QLabel(self.tab_231)
        self.label_visa_2_4.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_4.setFont(font)
        self.label_visa_2_4.setText(_fromUtf8(""))
        self.label_visa_2_4.setObjectName(_fromUtf8("label_visa_2_4"))
        self.label_chooseVisa_2_4 = QtGui.QLabel(self.tab_231)
        self.label_chooseVisa_2_4.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_4.setFont(font)
        self.label_chooseVisa_2_4.setObjectName(_fromUtf8("label_chooseVisa_2_4"))
        self.label_visaname_2_4 = QtGui.QLabel(self.tab_231)
        self.label_visaname_2_4.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_4.setFont(font)
        self.label_visaname_2_4.setObjectName(_fromUtf8("label_visaname_2_4"))
        self.pushButton_update_2_4 = QtGui.QPushButton(self.tab_231)
        self.pushButton_update_2_4.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_4.setFont(font)
        self.pushButton_update_2_4.setObjectName(_fromUtf8("pushButton_update_2_4"))
        self.pushButton_select_2_4 = QtGui.QPushButton(self.tab_231)
        self.pushButton_select_2_4.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_4.setFont(font)
        self.pushButton_select_2_4.setObjectName(_fromUtf8("pushButton_select_2_4"))
        self.pushButton_close_2_4 = QtGui.QPushButton(self.tab_231)
        self.pushButton_close_2_4.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_4.setFont(font)
        self.pushButton_close_2_4.setObjectName(_fromUtf8("pushButton_close_2_4"))
        self.tabWidget_visa.addTab(self.tab_231, _fromUtf8(""))
        self.tab_232 = QtGui.QWidget()
        self.tab_232.setObjectName(_fromUtf8("tab_232"))
        self.comboBox_visa_2_5 = QtGui.QComboBox(self.tab_232)
        self.comboBox_visa_2_5.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_5.setFont(font)
        self.comboBox_visa_2_5.setObjectName(_fromUtf8("comboBox_visa_2_5"))
        self.label_visa_2_5 = QtGui.QLabel(self.tab_232)
        self.label_visa_2_5.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_5.setFont(font)
        self.label_visa_2_5.setText(_fromUtf8(""))
        self.label_visa_2_5.setObjectName(_fromUtf8("label_visa_2_5"))
        self.label_chooseVisa_2_5 = QtGui.QLabel(self.tab_232)
        self.label_chooseVisa_2_5.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_5.setFont(font)
        self.label_chooseVisa_2_5.setObjectName(_fromUtf8("label_chooseVisa_2_5"))
        self.label_visaname_2_5 = QtGui.QLabel(self.tab_232)
        self.label_visaname_2_5.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_5.setFont(font)
        self.label_visaname_2_5.setObjectName(_fromUtf8("label_visaname_2_5"))
        self.pushButton_update_2_5 = QtGui.QPushButton(self.tab_232)
        self.pushButton_update_2_5.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_5.setFont(font)
        self.pushButton_update_2_5.setObjectName(_fromUtf8("pushButton_update_2_5"))
        self.pushButton_select_2_5 = QtGui.QPushButton(self.tab_232)
        self.pushButton_select_2_5.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_5.setFont(font)
        self.pushButton_select_2_5.setObjectName(_fromUtf8("pushButton_select_2_5"))
        self.pushButton_close_2_5 = QtGui.QPushButton(self.tab_232)
        self.pushButton_close_2_5.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_5.setFont(font)
        self.pushButton_close_2_5.setObjectName(_fromUtf8("pushButton_close_2_5"))
        self.tabWidget_visa.addTab(self.tab_232, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.comboBox_visa_2_6 = QtGui.QComboBox(self.tab_3)
        self.comboBox_visa_2_6.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_6.setFont(font)
        self.comboBox_visa_2_6.setObjectName(_fromUtf8("comboBox_visa_2_6"))
        self.label_visa_2_6 = QtGui.QLabel(self.tab_3)
        self.label_visa_2_6.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_6.setFont(font)
        self.label_visa_2_6.setText(_fromUtf8(""))
        self.label_visa_2_6.setObjectName(_fromUtf8("label_visa_2_6"))
        self.label_chooseVisa_2_6 = QtGui.QLabel(self.tab_3)
        self.label_chooseVisa_2_6.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_6.setFont(font)
        self.label_chooseVisa_2_6.setObjectName(_fromUtf8("label_chooseVisa_2_6"))
        self.label_visaname_2_6 = QtGui.QLabel(self.tab_3)
        self.label_visaname_2_6.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_6.setFont(font)
        self.label_visaname_2_6.setObjectName(_fromUtf8("label_visaname_2_6"))
        self.pushButton_update_2_6 = QtGui.QPushButton(self.tab_3)
        self.pushButton_update_2_6.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_6.setFont(font)
        self.pushButton_update_2_6.setObjectName(_fromUtf8("pushButton_update_2_6"))
        self.pushButton_select_2_6 = QtGui.QPushButton(self.tab_3)
        self.pushButton_select_2_6.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_6.setFont(font)
        self.pushButton_select_2_6.setObjectName(_fromUtf8("pushButton_select_2_6"))
        self.pushButton_close_2_6 = QtGui.QPushButton(self.tab_3)
        self.pushButton_close_2_6.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_6.setFont(font)
        self.pushButton_close_2_6.setObjectName(_fromUtf8("pushButton_close_2_6"))
        self.tabWidget_visa.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.comboBox_visa_2_7 = QtGui.QComboBox(self.tab_4)
        self.comboBox_visa_2_7.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_7.setFont(font)
        self.comboBox_visa_2_7.setObjectName(_fromUtf8("comboBox_visa_2_7"))
        self.label_visa_2_7 = QtGui.QLabel(self.tab_4)
        self.label_visa_2_7.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_7.setFont(font)
        self.label_visa_2_7.setText(_fromUtf8(""))
        self.label_visa_2_7.setObjectName(_fromUtf8("label_visa_2_7"))
        self.label_chooseVisa_2_7 = QtGui.QLabel(self.tab_4)
        self.label_chooseVisa_2_7.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_7.setFont(font)
        self.label_chooseVisa_2_7.setObjectName(_fromUtf8("label_chooseVisa_2_7"))
        self.label_visaname_2_7 = QtGui.QLabel(self.tab_4)
        self.label_visaname_2_7.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_7.setFont(font)
        self.label_visaname_2_7.setObjectName(_fromUtf8("label_visaname_2_7"))
        self.pushButton_update_2_7 = QtGui.QPushButton(self.tab_4)
        self.pushButton_update_2_7.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_7.setFont(font)
        self.pushButton_update_2_7.setObjectName(_fromUtf8("pushButton_update_2_7"))
        self.pushButton_select_2_7 = QtGui.QPushButton(self.tab_4)
        self.pushButton_select_2_7.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_7.setFont(font)
        self.pushButton_select_2_7.setObjectName(_fromUtf8("pushButton_select_2_7"))
        self.pushButton_close_2_7 = QtGui.QPushButton(self.tab_4)
        self.pushButton_close_2_7.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_7.setFont(font)
        self.pushButton_close_2_7.setObjectName(_fromUtf8("pushButton_close_2_7"))
        self.tabWidget_visa.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.comboBox_visa_2_8 = QtGui.QComboBox(self.tab_5)
        self.comboBox_visa_2_8.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_8.setFont(font)
        self.comboBox_visa_2_8.setObjectName(_fromUtf8("comboBox_visa_2_8"))
        self.label_visa_2_8 = QtGui.QLabel(self.tab_5)
        self.label_visa_2_8.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_8.setFont(font)
        self.label_visa_2_8.setText(_fromUtf8(""))
        self.label_visa_2_8.setObjectName(_fromUtf8("label_visa_2_8"))
        self.label_chooseVisa_2_8 = QtGui.QLabel(self.tab_5)
        self.label_chooseVisa_2_8.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_8.setFont(font)
        self.label_chooseVisa_2_8.setObjectName(_fromUtf8("label_chooseVisa_2_8"))
        self.label_visaname_2_8 = QtGui.QLabel(self.tab_5)
        self.label_visaname_2_8.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_8.setFont(font)
        self.label_visaname_2_8.setObjectName(_fromUtf8("label_visaname_2_8"))
        self.pushButton_update_2_8 = QtGui.QPushButton(self.tab_5)
        self.pushButton_update_2_8.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_8.setFont(font)
        self.pushButton_update_2_8.setObjectName(_fromUtf8("pushButton_update_2_8"))
        self.pushButton_select_2_8 = QtGui.QPushButton(self.tab_5)
        self.pushButton_select_2_8.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_8.setFont(font)
        self.pushButton_select_2_8.setObjectName(_fromUtf8("pushButton_select_2_8"))
        self.pushButton_close_2_8 = QtGui.QPushButton(self.tab_5)
        self.pushButton_close_2_8.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_8.setFont(font)
        self.pushButton_close_2_8.setObjectName(_fromUtf8("pushButton_close_2_8"))
        self.tabWidget_visa.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.comboBox_visa_2_9 = QtGui.QComboBox(self.tab_6)
        self.comboBox_visa_2_9.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_9.setFont(font)
        self.comboBox_visa_2_9.setObjectName(_fromUtf8("comboBox_visa_2_9"))
        self.label_visa_2_9 = QtGui.QLabel(self.tab_6)
        self.label_visa_2_9.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_9.setFont(font)
        self.label_visa_2_9.setText(_fromUtf8(""))
        self.label_visa_2_9.setObjectName(_fromUtf8("label_visa_2_9"))
        self.label_chooseVisa_2_9 = QtGui.QLabel(self.tab_6)
        self.label_chooseVisa_2_9.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_9.setFont(font)
        self.label_chooseVisa_2_9.setObjectName(_fromUtf8("label_chooseVisa_2_9"))
        self.label_visaname_2_9 = QtGui.QLabel(self.tab_6)
        self.label_visaname_2_9.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_9.setFont(font)
        self.label_visaname_2_9.setObjectName(_fromUtf8("label_visaname_2_9"))
        self.pushButton_update_2_9 = QtGui.QPushButton(self.tab_6)
        self.pushButton_update_2_9.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_9.setFont(font)
        self.pushButton_update_2_9.setObjectName(_fromUtf8("pushButton_update_2_9"))
        self.pushButton_select_2_9 = QtGui.QPushButton(self.tab_6)
        self.pushButton_select_2_9.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_9.setFont(font)
        self.pushButton_select_2_9.setObjectName(_fromUtf8("pushButton_select_2_9"))
        self.pushButton_close_2_9 = QtGui.QPushButton(self.tab_6)
        self.pushButton_close_2_9.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_9.setFont(font)
        self.pushButton_close_2_9.setObjectName(_fromUtf8("pushButton_close_2_9"))
        self.tabWidget_visa.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.comboBox_visa_2_10 = QtGui.QComboBox(self.tab_7)
        self.comboBox_visa_2_10.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2_10.setFont(font)
        self.comboBox_visa_2_10.setObjectName(_fromUtf8("comboBox_visa_2_10"))
        self.label_visa_2_10 = QtGui.QLabel(self.tab_7)
        self.label_visa_2_10.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2_10.setFont(font)
        self.label_visa_2_10.setText(_fromUtf8(""))
        self.label_visa_2_10.setObjectName(_fromUtf8("label_visa_2_10"))
        self.label_chooseVisa_2_10 = QtGui.QLabel(self.tab_7)
        self.label_chooseVisa_2_10.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2_10.setFont(font)
        self.label_chooseVisa_2_10.setObjectName(_fromUtf8("label_chooseVisa_2_10"))
        self.label_visaname_2_10 = QtGui.QLabel(self.tab_7)
        self.label_visaname_2_10.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2_10.setFont(font)
        self.label_visaname_2_10.setObjectName(_fromUtf8("label_visaname_2_10"))
        self.pushButton_update_2_10 = QtGui.QPushButton(self.tab_7)
        self.pushButton_update_2_10.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2_10.setFont(font)
        self.pushButton_update_2_10.setObjectName(_fromUtf8("pushButton_update_2_10"))
        self.pushButton_select_2_10 = QtGui.QPushButton(self.tab_7)
        self.pushButton_select_2_10.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2_10.setFont(font)
        self.pushButton_select_2_10.setObjectName(_fromUtf8("pushButton_select_2_10"))
        self.pushButton_close_2_10 = QtGui.QPushButton(self.tab_7)
        self.pushButton_close_2_10.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2_10.setFont(font)
        self.pushButton_close_2_10.setObjectName(_fromUtf8("pushButton_close_2_10"))
        self.tabWidget_visa.addTab(self.tab_7, _fromUtf8(""))
        self.label_device_2 = QtGui.QLabel(self.groupBox_secondaey_device)
        self.label_device_2.setGeometry(QtCore.QRect(30, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_device_2.setFont(font)
        self.label_device_2.setObjectName(_fromUtf8("label_device_2"))
        self.comboBox_device_2 = QtGui.QComboBox(self.groupBox_secondaey_device)
        self.comboBox_device_2.setGeometry(QtCore.QRect(20, 40, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_device_2.setFont(font)
        self.comboBox_device_2.setObjectName(_fromUtf8("comboBox_device_2"))
        self.comboBox_device_2.addItem(_fromUtf8(""))
        self.comboBox_device_2.addItem(_fromUtf8(""))
        self.comboBox_device_2.addItem(_fromUtf8(""))
        self.comboBox_device_2.addItem(_fromUtf8(""))
        self.comboBox_device_2.addItem(_fromUtf8(""))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_secondary_sweep)
        self.groupBox_9.setGeometry(QtCore.QRect(380, 300, 541, 61))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_condition_2 = QtGui.QLabel(self.groupBox_9)
        self.label_condition_2.setGeometry(QtCore.QRect(10, 20, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_condition_2.setFont(font)
        self.label_condition_2.setText(_fromUtf8(""))
        self.label_condition_2.setObjectName(_fromUtf8("label_condition_2"))
        self.groupBox_input_2 = QtGui.QGroupBox(self.groupBox_secondary_sweep)
        self.groupBox_input_2.setGeometry(QtCore.QRect(380, 30, 541, 271))
        self.groupBox_input_2.setTitle(_fromUtf8(""))
        self.groupBox_input_2.setObjectName(_fromUtf8("groupBox_input_2"))
        self.label_48 = QtGui.QLabel(self.groupBox_input_2)
        self.label_48.setGeometry(QtCore.QRect(20, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.textEdit_steps_2 = QtGui.QTextEdit(self.groupBox_input_2)
        self.textEdit_steps_2.setGeometry(QtCore.QRect(20, 40, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_steps_2.setFont(font)
        self.textEdit_steps_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_steps_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_steps_2.setTabStopWidth(80)
        self.textEdit_steps_2.setCursorWidth(2)
        self.textEdit_steps_2.setObjectName(_fromUtf8("textEdit_steps_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_input_2)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_steps_2 = QtGui.QLabel(self.groupBox_input_2)
        self.label_steps_2.setGeometry(QtCore.QRect(130, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_steps_2.setFont(font)
        self.label_steps_2.setText(_fromUtf8(""))
        self.label_steps_2.setObjectName(_fromUtf8("label_steps_2"))
        self.pushButton_clear_2 = QtGui.QPushButton(self.groupBox_input_2)
        self.pushButton_clear_2.setEnabled(False)
        self.pushButton_clear_2.setGeometry(QtCore.QRect(400, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clear_2.setFont(font)
        self.pushButton_clear_2.setObjectName(_fromUtf8("pushButton_clear_2"))
        self.pushButton_plot_2 = QtGui.QPushButton(self.groupBox_input_2)
        self.pushButton_plot_2.setGeometry(QtCore.QRect(290, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_plot_2.setFont(font)
        self.pushButton_plot_2.setObjectName(_fromUtf8("pushButton_plot_2"))
        self.textEdit_input_2 = QtGui.QTextEdit(self.groupBox_input_2)
        self.textEdit_input_2.setGeometry(QtCore.QRect(230, 40, 291, 171))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_input_2.setFont(font)
        self.textEdit_input_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_input_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_input_2.setTabStopWidth(80)
        self.textEdit_input_2.setCursorWidth(2)
        self.textEdit_input_2.setObjectName(_fromUtf8("textEdit_input_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_input_2)
        self.label_5.setGeometry(QtCore.QRect(230, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.groupBox_stepplot_2 = QtGui.QGroupBox(self.groupBox_secondary_sweep)
        self.groupBox_stepplot_2.setGeometry(QtCore.QRect(20, 360, 901, 651))
        self.groupBox_stepplot_2.setObjectName(_fromUtf8("groupBox_stepplot_2"))
        self.widget_2 = QtGui.QWidget(self.groupBox_stepplot_2)
        self.widget_2.setGeometry(QtCore.QRect(0, 10, 901, 651))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.mplwidget_2 = MatplotlibWidget(self.widget_2)
        self.mplwidget_2.setGeometry(QtCore.QRect(410, 320, 16, 16))
        self.mplwidget_2.setObjectName(_fromUtf8("mplwidget_2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_primary_sweep_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_primary_sweep_2.setGeometry(QtCore.QRect(0, 10, 931, 1021))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_primary_sweep_2.setFont(font)
        self.groupBox_primary_sweep_2.setObjectName(_fromUtf8("groupBox_primary_sweep_2"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_primary_sweep_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 911, 841))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_secondary_sweep_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_secondary_sweep_2.setGeometry(QtCore.QRect(930, 10, 931, 1021))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_secondary_sweep_2.setFont(font)
        self.groupBox_secondary_sweep_2.setObjectName(_fromUtf8("groupBox_secondary_sweep_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox_secondary_sweep_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 160, 911, 851))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.tabWidget_2.addTab(self.tab_9, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionArray_Builder = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionArray_Builder.setFont(font)
        self.actionArray_Builder.setObjectName(_fromUtf8("actionArray_Builder"))
        self.actionAgilent_Single_scan = QtGui.QAction(MainWindow)
        self.actionAgilent_Single_scan.setObjectName(_fromUtf8("actionAgilent_Single_scan"))
        self.actionKeithley_Single_scan = QtGui.QAction(MainWindow)
        self.actionKeithley_Single_scan.setObjectName(_fromUtf8("actionKeithley_Single_scan"))
        self.actionKeithley__Sweep = QtGui.QAction(MainWindow)
        self.actionKeithley__Sweep.setObjectName(_fromUtf8("actionKeithley__Sweep"))
        self.actionLockIn_Single_Scan = QtGui.QAction(MainWindow)
        self.actionLockIn_Single_Scan.setObjectName(_fromUtf8("actionLockIn_Single_Scan"))
        self.actionResonant_Single_Scan = QtGui.QAction(MainWindow)
        self.actionResonant_Single_Scan.setObjectName(_fromUtf8("actionResonant_Single_Scan"))
        self.actionKeithley_Stepper_Single_Scan = QtGui.QAction(MainWindow)
        self.actionKeithley_Stepper_Single_Scan.setObjectName(_fromUtf8("actionKeithley_Stepper_Single_Scan"))
        self.actionSee_Visa_List = QtGui.QAction(MainWindow)
        self.actionSee_Visa_List.setObjectName(_fromUtf8("actionSee_Visa_List"))
        self.actionTwo_s_with_Lock_in = QtGui.QAction(MainWindow)
        self.actionTwo_s_with_Lock_in.setObjectName(_fromUtf8("actionTwo_s_with_Lock_in"))
        self.actionSweep_Scan = QtGui.QAction(MainWindow)
        self.actionSweep_Scan.setObjectName(_fromUtf8("actionSweep_Scan"))
        self.actionLockInSweep = QtGui.QAction(MainWindow)
        self.actionLockInSweep.setObjectName(_fromUtf8("actionLockInSweep"))
        self.actionDouble_Lock_In = QtGui.QAction(MainWindow)
        self.actionDouble_Lock_In.setObjectName(_fromUtf8("actionDouble_Lock_In"))
        self.actionVoltage_Bias = QtGui.QAction(MainWindow)
        self.actionVoltage_Bias.setObjectName(_fromUtf8("actionVoltage_Bias"))
        self.actionCurrent_Bias = QtGui.QAction(MainWindow)
        self.actionCurrent_Bias.setObjectName(_fromUtf8("actionCurrent_Bias"))
        self.actionJV_1 = QtGui.QAction(MainWindow)
        self.actionJV_1.setObjectName(_fromUtf8("actionJV_1"))
        self.actionJV_2 = QtGui.QAction(MainWindow)
        self.actionJV_2.setObjectName(_fromUtf8("actionJV_2"))
        self.actionJV_3 = QtGui.QAction(MainWindow)
        self.actionJV_3.setObjectName(_fromUtf8("actionJV_3"))
        self.actionJS_1 = QtGui.QAction(MainWindow)
        self.actionJS_1.setObjectName(_fromUtf8("actionJS_1"))
        self.actionJS_2 = QtGui.QAction(MainWindow)
        self.actionJS_2.setObjectName(_fromUtf8("actionJS_2"))
        self.actionRS_1 = QtGui.QAction(MainWindow)
        self.actionRS_1.setObjectName(_fromUtf8("actionRS_1"))
        self.actionRS_2 = QtGui.QAction(MainWindow)
        self.actionRS_2.setObjectName(_fromUtf8("actionRS_2"))
        self.actionJS_3 = QtGui.QAction(MainWindow)
        self.actionJS_3.setObjectName(_fromUtf8("actionJS_3"))
        self.actionRS_3 = QtGui.QAction(MainWindow)
        self.actionRS_3.setObjectName(_fromUtf8("actionRS_3"))
        self.actionBW_1 = QtGui.QAction(MainWindow)
        self.actionBW_1.setObjectName(_fromUtf8("actionBW_1"))
        self.actionBW_2 = QtGui.QAction(MainWindow)
        self.actionBW_2.setObjectName(_fromUtf8("actionBW_2"))
        self.actionBW_3 = QtGui.QAction(MainWindow)
        self.actionBW_3.setObjectName(_fromUtf8("actionBW_3"))
        self.actionST_1 = QtGui.QAction(MainWindow)
        self.actionST_1.setObjectName(_fromUtf8("actionST_1"))
        self.actionST_2 = QtGui.QAction(MainWindow)
        self.actionST_2.setObjectName(_fromUtf8("actionST_2"))
        self.actionST_3 = QtGui.QAction(MainWindow)
        self.actionST_3.setObjectName(_fromUtf8("actionST_3"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_visa.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_primary_sweep.setTitle(_translate("MainWindow", "Primary Sweep", None))
        self.label_visaname_1.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_1.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_1.setText(_translate("MainWindow", "Select", None))
        self.label_chooseVisa_1.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.pushButton_close_1.setText(_translate("MainWindow", "Close", None))
        self.label_device_1.setText(_translate("MainWindow", "Device:", None))
        self.comboBox_device_1.setItemText(0, _translate("MainWindow", "Agilent 34460A", None))
        self.comboBox_device_1.setItemText(1, _translate("MainWindow", "Keithley 2450", None))
        self.comboBox_device_1.setItemText(2, _translate("MainWindow", "Magnet Model 430", None))
        self.comboBox_device_1.setItemText(3, _translate("MainWindow", "Yokogawa GS200", None))
        self.label_47.setText(_translate("MainWindow", "Step Number:", None))
        self.textEdit_steps_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Start 0</p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "Steps, Repeat Step, Peak:", None))
        self.pushButton_clear_1.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_plot_1.setText(_translate("MainWindow", "Plot", None))
        self.textEdit_input_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "Input:", None))
        self.groupBox_stepplot_1.setTitle(_translate("MainWindow", "Plot", None))
        self.groupBox_condition_1.setTitle(_translate("MainWindow", "Condition", None))
        self.groupBox_secondary_sweep.setTitle(_translate("MainWindow", "Secondary Sweep", None))
        self.label_chooseVisa_2_1.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.pushButton_select_2_1.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_2_1.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_close_2_1.setText(_translate("MainWindow", "Close", None))
        self.pushButton_update_2_1.setText(_translate("MainWindow", "Update", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_228), _translate("MainWindow", "Visa1", None))
        self.label_chooseVisa_2_2.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.label_visaname_2_2.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_2_2.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_2_2.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_2_2.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_229), _translate("MainWindow", "Visa2", None))
        self.label_chooseVisa_2_3.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.label_visaname_2_3.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_2_3.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_2_3.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_2_3.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_230), _translate("MainWindow", "Visa3", None))
        self.label_chooseVisa_2_4.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.label_visaname_2_4.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_2_4.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_2_4.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_2_4.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_231), _translate("MainWindow", "Visa4", None))
        self.label_chooseVisa_2_5.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.label_visaname_2_5.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_2_5.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_2_5.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_2_5.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_232), _translate("MainWindow", "Visa5", None))
        self.label_chooseVisa_2_6.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.label_visaname_2_6.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_2_6.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_2_6.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_2_6.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_3), _translate("MainWindow", "Visa6", None))
        self.label_chooseVisa_2_7.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.label_visaname_2_7.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_2_7.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_2_7.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_2_7.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_4), _translate("MainWindow", "Visa7", None))
        self.label_chooseVisa_2_8.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.label_visaname_2_8.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_2_8.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_2_8.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_2_8.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_5), _translate("MainWindow", "Visa8", None))
        self.label_chooseVisa_2_9.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.label_visaname_2_9.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_2_9.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_2_9.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_2_9.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_6), _translate("MainWindow", "Visa9", None))
        self.label_chooseVisa_2_10.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.label_visaname_2_10.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_update_2_10.setText(_translate("MainWindow", "Update", None))
        self.pushButton_select_2_10.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_2_10.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_7), _translate("MainWindow", "Visa10", None))
        self.label_device_2.setText(_translate("MainWindow", "Device:", None))
        self.comboBox_device_2.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBox_device_2.setItemText(1, _translate("MainWindow", "Agilent 34460A", None))
        self.comboBox_device_2.setItemText(2, _translate("MainWindow", "Keithley 2450", None))
        self.comboBox_device_2.setItemText(3, _translate("MainWindow", "Magnet Model 430", None))
        self.comboBox_device_2.setItemText(4, _translate("MainWindow", "Yokogawa GS200", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Condition", None))
        self.label_48.setText(_translate("MainWindow", "Step Number:", None))
        self.textEdit_steps_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Start 0</p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "Steps, Repeat Step, Peak:", None))
        self.pushButton_clear_2.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_plot_2.setText(_translate("MainWindow", "Plot", None))
        self.textEdit_input_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "Input:", None))
        self.groupBox_stepplot_2.setTitle(_translate("MainWindow", "Plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Setup", None))
        self.groupBox_primary_sweep_2.setTitle(_translate("MainWindow", "Primary Sweep", None))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.groupBox_secondary_sweep_2.setTitle(_translate("MainWindow", "Secondary Sweep", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Tab 1", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Tab 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scan", None))
        self.actionArray_Builder.setText(_translate("MainWindow", "Array Builder", None))
        self.actionAgilent_Single_scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionKeithley_Single_scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionKeithley__Sweep.setText(_translate("MainWindow", " Sweep", None))
        self.actionLockIn_Single_Scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionResonant_Single_Scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionKeithley_Stepper_Single_Scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionSee_Visa_List.setText(_translate("MainWindow", "See Visa List", None))
        self.actionTwo_s_with_Lock_in.setText(_translate("MainWindow", "Two s with Lock-in", None))
        self.actionSweep_Scan.setText(_translate("MainWindow", "Sweep Scan", None))
        self.actionLockInSweep.setText(_translate("MainWindow", "Sweep Scan", None))
        self.actionDouble_Lock_In.setText(_translate("MainWindow", "Double Lock-In", None))
        self.actionVoltage_Bias.setText(_translate("MainWindow", "Voltage", None))
        self.actionCurrent_Bias.setText(_translate("MainWindow", "Current", None))
        self.actionJV_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionJV_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionJV_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionJS_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionJS_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionRS_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionRS_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionJS_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionRS_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionBW_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionBW_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionBW_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionST_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionST_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionST_3.setText(_translate("MainWindow", "Program 3", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

